- name: validate-dependabot
  uses: marocchino/validate-dependabot@v1.1.0

name: dependabot validate

on:
  pull_request:
    paths:
      - ".github/dependabot.yml"
      - ".github/workflows/dependabot-validate.yml"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: marocchino/validate-dependabot@v1
        id: validate
      - uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          header: validate-dependabot
          message: ${{ steps.validate.outputs.markdown }}
          
          name: 'validate-dependabot'
description: 'validate dependabot yaml'
author: 'marocchino'
inputs:
  path:
    required: true
    description: 'path of dependabot yaml file'
    default: '.github/dependabot.yml'
  success_message:
    required: true
    description: 'display on success'
    default: 'âœ…dependabot config looks good ğŸ‘'
  failure_message:
    required: true
    description: 'display on failure'
    default: 'ğŸš« dependabot errors'
runs:
  using: 'node12'
  main: 'dist/index.js'
