- name: update-github-actions-secret
  uses: ekowcharles/update-github-actions-secret@0.0.5

- name: Create or update Github Actions secret
  uses: ekowcharles/update-github-actions-secret@v1
  env:
    OWNER: 'AdamOswald'
    REPOSITORY: 'Ai-test'
    ACCESS_TOKEN: 'et984tnGHtet829je'
    SECRET_NAME: 
    SECRET_VALUE: 
    
    name: update-github-actions-secret
description: "This action creates a new github actions secret or updates an existing one."
author: 'Charles Boadu Jr'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'lock'  
  color: 'purple'
  
  
